# ---------------------------------------------------------------------------
# Database — created on first link, preserved on unlink.
#
# On re-links (database already exists in PostgreSQL but not in tfstate),
# do_tofu runs "tofu import postgresql_database.app <db_name>" before apply,
# so no data is lost. prevent_destroy ensures tofu destroy never drops the DB.
# ---------------------------------------------------------------------------

resource "postgresql_database" "app" {
  name  = var.db_name
  owner = var.master_username

  lifecycle {
    prevent_destroy = true
  }
}

# ---------------------------------------------------------------------------
# App user (password generated by Terraform, stable across re-applies)
# The keepers block ensures the password is only regenerated if link_id
# changes (which it won't), preserving credentials on update workflows.
# ---------------------------------------------------------------------------

resource "random_password" "user" {
  length  = 32
  special = false
  keepers = {
    link_id = var.link_id
  }
}

resource "postgresql_role" "app_user" {
  name     = var.db_username
  password = random_password.user.result
  login    = true
}

# ---------------------------------------------------------------------------
# Permissions
# ---------------------------------------------------------------------------

resource "postgresql_grant" "connect" {
  database    = postgresql_database.app.name
  role        = postgresql_role.app_user.name
  object_type = "database"
  privileges  = ["CONNECT"]
}

resource "postgresql_grant" "schema_usage" {
  database    = postgresql_database.app.name
  role        = postgresql_role.app_user.name
  schema      = "public"
  object_type = "schema"
  privileges  = local.schema_privileges[var.access_level]
}

# Grant on existing tables
resource "postgresql_grant" "tables" {
  database    = postgresql_database.app.name
  role        = postgresql_role.app_user.name
  schema      = "public"
  object_type = "table"
  privileges  = local.table_privileges[var.access_level]
}

# Grant on future tables (default privileges applied by master user)
resource "postgresql_default_privileges" "tables" {
  role        = postgresql_role.app_user.name
  database    = postgresql_database.app.name
  schema      = "public"
  owner       = var.master_username
  object_type = "table"
  privileges  = local.table_privileges[var.access_level]
}

# Grant USAGE on existing sequences (needed for INSERT on serial/bigserial columns)
resource "postgresql_grant" "sequences" {
  database    = postgresql_database.app.name
  role        = postgresql_role.app_user.name
  schema      = "public"
  object_type = "sequence"
  privileges  = ["USAGE", "SELECT"]
}

# Grant USAGE on future sequences
resource "postgresql_default_privileges" "sequences" {
  role        = postgresql_role.app_user.name
  database    = postgresql_database.app.name
  schema      = "public"
  owner       = var.master_username
  object_type = "sequence"
  privileges  = ["USAGE", "SELECT"]
}
