name: tests

on:
  pull_request:
    branches:
      - main

jobs:
  do-tofu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [rds-postgres-db, rds-postgres-server]
    steps:
      - uses: actions/checkout@v7
      - run: bash tests/do_tofu_version.sh ${{ matrix.package }}/scripts/aws/do_tofu

  provider-lookup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: bash tests/provider_lookup.sh

  external-kms-key:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: bash tests/external_kms_key.sh

  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: sudo apt-get install -y bats
      - run: bats rds-postgres-server/scripts/tests/aws

  requirements-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: opentofu/setup-opentofu@v1
      - working-directory: rds-postgres-server/specs/requirements/aws
        run: |
          tofu init -backend=false
          tofu test

  link-outputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: bash tests/link_outputs.sh

  instance-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: bash tests/instance_name.sh
