name: tests

on:
  pull_request:
    branches:
      - main

jobs:
  do-tofu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [rds-postgres-db, rds-postgres-server]
    steps:
      - uses: actions/checkout@v4
      - run: bash tests/do_tofu_version.sh ${{ matrix.package }}/scripts/aws/do_tofu
